wrapperVersion=3.3.4
distributionType=only-script
<<<<<<< HEAD
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
=======
<<<<<<< HEAD
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.15/apache-maven-3.9.15-bin.zip
=======
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
>>>>>>> af8857d2968cdab665bb6ba7f90c83f28f906b62
>>>>>>> e610f086459a532558683d82e798e72033ba56b6
